apps/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # スラッシュだけで行けるよう
                       url(r'^$', include('entries.urls')),
                       url(r'^entries/', include('entries.urls')),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)',
                             'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT,
                              'show_indexes': True}),
                            # {'document_root': settings.MEDIA_URL +
                            # {'document_root' : os.path.dirname(__file__) +
                            # '/static'}),
    )

entries/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include
from entries.models import Entry, News
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView

info_dict = {
    'queryset': Entry.objects.all(),
}

urlpatterns = patterns('',
                       # select
                       (r'^$', ListView.as_view(queryset=News.objects.all())),
                       # BBS
                       # create
                       (r'^create/$',
                        CreateView.as_view(model=Entry, success_url='/entries/bbs/')),
                       # edit
                       (r'^detail/(?P<pk>\d+)/$',
                        DetailView.as_view(queryset=Entry.objects.all())),
                       # update
                       (r'^update/(?P<pk>\d+)/$',
                        UpdateView.as_view(model=Entry)),
                       # delete
                       (r'^delete/(?P<pk>\d+)/$',
                        DeleteView.as_view(model=Entry, success_url='/entries/bbs/')),
                       # NEWS
                       # create
                       (r'^create_news/$',
                        CreateView.as_view(model=News, success_url='/entries/')),
                       # edit
                       (r'^detail_news/(?P<pk>\d+)/$',
                        DetailView.as_view(queryset=News.objects.all())),
                       # update
                       (r'^update_news/(?P<pk>\d+)/$',
                        UpdateView.as_view(model=News)),
                       # delete
                       (r'^delete_news/(?P<pk>\d+)/$',
                        DeleteView.as_view(model=News, success_url='/entries/')),

                       # normal pages
                       (r'^mail/', TemplateView.as_view(template_name="pages/mail.html")),
                       (r'^member/', TemplateView.as_view(template_name="pages/member.html")),
                       (r'^bbs/', ListView.as_view(queryset=Entry.objects.all())),
                       (r'^schedule/', TemplateView.as_view(template_name="pages/schedule.html")),
                       (r'^master/', TemplateView.as_view(template_name="pages/master.html")),
                       (r'^links/', TemplateView.as_view(template_name="pages/links.html")),
                       (r'^edogawa/', TemplateView.as_view(template_name="pages/edogawa.html")),
                       (r'^shinjukuclub/', TemplateView.as_view(template_name="pages/shinjukuclub.html")),
                       (r'^mail/', TemplateView.as_view(template_name="pages/mail.html")),
                       # comment for BBS
                       (r'^comments/', include('django.contrib.comments.urls')),
                       # base.htmlのプルダウン言語セットに必須
                       (r'^i18n/', include('django.conf.urls.i18n')),
)

# login / logout
urlpatterns += patterns('',
                        (r'login/$', 'django.contrib.auth.views.login',
                         {'template_name': 'entries/registration/login.html'}),
                        (r'^logout/$',
                         'django.contrib.auth.views.logout',
                         {'template_name': 'entries/registration/logout.html'}),
)

entries/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
class Entry(models.Model):
    """
    エントリのモデル
    """
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.EmailField(help_text='A valid e-mail address, please.')
    content = models.TextField(max_length=1000)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/entries/detail/%i" % self.id


class News(models.Model):
    """
    ニュース
    """
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    date = models.DateField(max_length=None)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/entries/detail_news/%i" % self.id


class Comment(models.Model):
    """
    エントリに対するコメントのモデル
    """
    # スレッド
    entry = models.ForeignKey(Entry, verbose_name=u'スレッド')
    name = models.CharField(max_length=100, verbose_name=u'名前')
    email = models.EmailField(help_text='A valid e-mail address, please.')
    # メッセージ
    message = models.CharField(u'メッセージ', max_length=200, blank=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'コメント'

    def __unicode__(self):
        return self.message

    def get_absolute_url(self):
        return "/entries/detail/%i" % self.id

entries/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
from django.forms import ModelForm
from entries.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ('entry', )

entries/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import render_to_response, get_object_or_404
from entries.models import Entry, Comment
from entries.forms import CommentForm
# TODO: 今後使う？
from django.http import HttpResponse, Http404
from django.utils.translation import get_language, activate, ugettext_lazy as _


class EntryView(ListView):
    context_object_name = "object_list"
    queryset = Entry.objects.all()


class EntryDetailView(DetailView):
    queryset = Entry.objects.all()
    model = Entry

    def get_object(self):
        """
        :return:
        """
        # Call the superclass
        object = super(EntryDetailView, self).get_object
        # Record the last accessed date
        # object.last_accessed = timezone.now()
        # object.save()
        # Return the object
        return object

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['comment_list'] = Comment.objects.all()
        return context


def entry_detail(request, entry_id):
    '''
    指定したスレッドを表示する。
    参考
    http://www.gesource.jp/programming/python/django/t002.html
    :param request: リクエスト
    :param entry_id: エントリID
    '''
    # 表示するエントリ
    entry = get_object_or_404(Entry, pk=entry_id)

    # コメントの登録処理
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # コメントを登録
            comment = form.save(cosmmit=False)
            comment.thread = entry
            comment.save()
            form = CommentForm()  # フォームの初期化
    else:
        form = CommentForm()
    # スレッドのコメント
    comment_list = entry.comment_set.all().order_by('id')
    return TemplateView.as_view(template_name='entries/entry_detail.html',
                                extra_context=
                                {'object': entry,
                                 'comment_list': comment_list,
                                 'form': form})

apps/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
  <head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="テコンドー,ミョンソン・テコンドー,WTFテコンドー,テコンドー新宿" content="テコンドー" />
    <meta name="description" content="東京都で活動するWTFテコンドー教室" />
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
    <title>{% trans "myung seong taekwondo" %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/base_style.css" media="all" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script> 
    <script type="text/javascript" src="{{ STATIC_URL }}js/spreadsheet.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}css/jquery-ui-1.9.0.custom.min.css" />
  </head>
  <body>
    <!-- メインコンテンツ部分 -->
    <div id="main">
      <!-- メインヘッダー部分 -->
      <div id="header">
        <div id="header-inner">
          <table border="0" align="" cellpadding="0" cellspacing="0" width="780">
            <tr>
              <td>
                <div id="table-left">
                  <!-- TODO: -->
                  <a href="http://www.myungseong-tkd.com/">
                    <img src="{{ STATIC_URL }}img/{{ LANGUAGE_CODE }}/toplogo.png" alt="ミョンソン・テコンドー"
                         width="300" height="55" border="0" />
                  </a>
                </div>
              </td>
              <td>
                <div id="table-right"><img src="{{ STATIC_URL }}img/icon.gif" alt="icon" border="0" />
                  <a href="http://myonson-tkd.blogspot.com/" target="_blank">{% trans "gymblog" %}</a>
                  <img src="{{ STATIC_URL }}img/icon.gif" alt="icon" border="0" />
                  <a href="/entries/mail/">{% trans "inquiry" %}</a>
                </div>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <!-- プルダウン言語セット -->
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="nexta" type="hidden" value="{{ redirect_to }}" />
        <!--input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" /-->
        <select name="language">
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
          {{ language.name_local }} ({{ language.code }})
        </option>
        {% endfor %}
        </select>
        <input type="submit" value="Go" />
      </form>
      <!-- メインヘッダー終わり -->
      <div>
        {% if user.is_anonymous %}
        <dd div class="operation">
            {% load l10n %}
            {% trans "myung seong taekwondo" %}
          <a href="/entries/login">{% trans "login" %}</a>
        </dd>
        <hr />
        {% else %}
        <p>username: <b>{{ user.username }}</b>
          <a href="/entries/logout/"> [{% trans "logout" %}]</a>
        </p>
        {% endif %}
      </div>
      <div id="header-menu">
        <ul>
          <li id="home"><a href="/entries/">{% trans "home" %}</a></li>
          <li><a href="/entries/member/">{% trans "admission" %}</a></li>
          <li><a href="/entries/schedule/">{% trans "training" %}</a></li>
          <li><a href="/entries/master/">{% trans "masterintro" %}</a></li>
          <li><a href="/entries/bbs/">{% trans "bbs" %}</a></li>
          <li><a href="/entries/links/">{% trans "links" %}</a></li>
          <li id="contact"><a href="/entries/mail/">{% trans "inquiry" %}</a></li>
        </ul>
      </div>
      <!-- トップコンテンツ部分 -->
      <!-- コンテンツ内部 -->
      <div id="container">
        {% block main %}

        {% endblock main %}

        <br />
        <!-- コンテンツ内部 終わり -->
      <!-- サイドメニュー部分 -->
      <div id="menu">
        <h2>{% trans "gymguide" %}</h2>
        <p>
          <!-- TODO: 管理者のみ表示 -->
          <a href="/admin/">{% trans "admin" %}</a><br />
          <a href="/entries/">{% trans "home" %}</a><br />
          <a href="/entries/member/">{% trans "admission" %}</a><br />
          <a href="/entries/schedule/">{% trans "shinjukugym" %}{% trans "training" %}</a><br />
          <a href="/entries/edogawa/">{% trans "edogawaclub" %}{% trans "training" %}</a><br />
          <a href="/entries/shinjukuclub/">{% trans "shinjukuclub" %}{% trans "training" %}</a><br />
          <a href="/entries/master/">{% trans "masterintro" %}</a><br />
          <a href="/entries/mail/">{% trans "inquiry" %}</a><br />
        </p>
        <h2>{% trans "mobileedition" %}</h2>
        <br />
        <img src="{{ STATIC_URL }}img/{{ LANGUAGE_CODE }}/qr.png" width="165" height="70" /> <br />
        </p>
        <h2>{% trans "sistergym" %}</h2>
        <p><a href="http://www.j-taekwondo.com" target="_blank"><img src="{{ STATIC_URL }}img/j-taekwondo150_bana.gif"
           alt="テコンドー" width="150" height="60" border="0" /></a>
        <h2>{% trans "gymblog" %}</h2>
        <p>
          <script language="javascript" src="http://rss.tc/feed/RssReader.aspx?url=http%3a%2f%2fmyonson-tkd.blogspot.com%2ffeeds%2fposts%2fdefault%3falt%3drss&amp;displayRow=10&amp;enc=3&amp;dispTitle=true&amp;dispTime=false&amp;id=9093"></script>
          <div style="font-size: 10px; text-align: right; margin: 2px ">Powered by <a href="http://rss.tc/" target="_top">
            <img src="http://rss.tc/images/rsstcicon.gif" alt="RSSリスティング" width="80" height="15" border="0" align="absbottom" />
          </a>
        </div>
      </div>
      <!-- サイドメニュー部分 終わり -->
      </div>
      <!-- トップコンテンツ部分 終わり -->
      <!-- フッター部分 -->
      <div id="footer"> Copyright (C) 2011 myungseong-tkd.com All Rights Reserved.</div>
      <!-- フッター部分 終わり -->
    </div>
    <!-- メインコンテンツ部分 終わり -->
  </body>
</html>

entries/templates/comments/form.html
{% load comments %}
{#% load markup %#}
{% load i18n %}

{% block title %}Preview Comment{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
   {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
    {% if form.errors %}
    <h2>{% blocktrans count form.errors|length as counter %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h2>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
    <table> 
    {% for field in form %}
      {% if field.is_hidden %}
        <tr><td>{{ field }}</td></td></tr>
       {% else %}
        {% if field.errors %}<tr><td colspan="2">{{ field.errors }}</td></tr>{% endif %}
          <tr{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}><td>{{ field.label_tag }}</td><td>{{ field }}</td></tr>
      {% endif %}
    {% endfor %}
    </table>    
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </form>
{% endblock %}

entries/templates/comments/posted.html
{% extends "entries/base_entries.html" %}

{% block entry_content %}
{% load comments %}

{% block title %}Comment Posted{% endblock %}

{% block content %}
<h2 class="title">Comment Posted</h2>
<div class="post">
<div class="entry">
<p>Your comment was posted succesfully
{% if comment.is_public %}
 - you can see it by <a href="{{comment.content_object.get_absolute_url}}">returning to the post</a>.
{% else %}
 - it has been held for moderation and, if deemed appropriate, will be approved in due course.
{% endif %}
</p>
</div> 
</div>
{% endblock %}
{% endblock %}

entries/templates/comments/preview.html
{% extends "entries/base_entries.html" %}
{% load comments %}
{#% load markup %#}
{% load i18n %}

{% block entry_content %}
{% block title %}Preview Comment{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
   {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
    {% if form.errors %}
    <h2>{% blocktrans count form.errors|length as counter %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h2>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
<table> 
    {% for field in form %}
      {% if field.is_hidden %}
        <tr><td>{{ field }}</td></td></tr>
       {% else %}
        {% if field.errors %}<tr><td colspan="2">{{ field.errors }}</td></tr>{% endif %}
          <tr{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}><td>{{ field.label_tag }}</td><td>{{ field }}</td></tr>
      {% endif %}
    {% endfor %}
</table>    
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </form>
{% endblock %}
{% endblock %}

entries/templates/entries/base_entries.html
{% extends "base.html" %}
{% block main %}
{% load i18n %}

<div id="contents">

<h3>{% trans "bbs" %}</h3>
<hr />
{% block entry_content %}
{% endblock entry_content %}

<hr />
</div>
{% endblock main %}

entries/templates/entries/entry_confirm_delete.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}

{# if not user.is_anonymous #}
<form method="post" action="." accept-charset="utf-8">{% csrf_token %}
  <p>削除します。よろしいですか？</p><br />

  <input type="submit" />
  <input type="button" value="いいえ" onClick="location.href='/entries/'" />
</form>
<br />
{# endif #}
{% endblock %}

entries/templates/entries/entry_detail.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}
{% load i18n %}
<dt>
  <b>{{ object.title }}</b>
</dt>

<dd>
  {{ object.content }}
</dd>

<dd div class="operation">
  [<a href="/entries/update/{{ object.id }}">{% trans "edit" %}</a>]
  [<a href="/entries/delete/{{ object.id }}">{% trans "delete" %}</a>]
</dd>

<hr />
{% for comment in comment_list %}
  <li>
    {{ comment.message }}<br />
    ({{ comment.pub_date|date:"Y/m/d h:i:s" }})
  </li>
{% endfor %}

{% load comments %}
<h2><a name="comments" href="#"></a>Comments</h2>
{% get_comment_list for object as comment_list %}
{% for comment in comment_list %}
<p class="date">On {{comment.submit_date|date:"F j,Y" }}, {{ comment.user_name}} said:</p>
<blockquote>
{{comment.comment}}
</blockquote>
{% endfor %}

<div id="add_comment">
<h2>{% trans "add comment" %}</h2>
{% render_comment_form for object %}
</div>

{% endblock %}

entries/templates/entries/entry_form.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}
{% load i18n %}
{% if object %}
<h3>{% trans "edit" %}</h3><br />
{% else %}
<h3>{% trans "new" %}</h3><br />
{% endif %}

{% if form.has_errors %}
  {% for field in form.fields %}
    {% if fields.error %}
      {{ field.error}}
    {% endif %}

  {% endfor %}
{% endif %}

<div class="validation">
  <form action="." method="post" accept-charset="utf-8">{% csrf_token %}
    <label for="id_title">{% trans "title" %}</label>{{ form.title }}
    {% if form.title.errors %}
    <p>
      <error> {{ form.title.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_email">{% trans "email" %}</label>{{ form.email }}
    {% if form.email.errors %}
    <p>
      <error> {{ form.email.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_name">{% trans "name" %}</label>{{ form.name }}
    {% if form.name.errors %}
    <p>
      <error> {{ form.name.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_enable_comments">{% trans "comment" %}</label>{{ form.enable_comments }}
    {% if form.enable_comments.errors %}
    <p>
      <error> {{ form.enable_comments.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_content">{% trans "content" %}</label>{{ form.content }}
    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    <br />
    {% endif %}
    <p><input type="submit" value="{% trans "save" %}" /></p><br />
  </form>
</div>
{% endblock %}

entries/templates/entries/entry_list.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}
{% load i18n %}

<!-- BBS一覧 -->
{% if object_list.count < 1 %}
  <b>{% trans "no entry" %}</b>
{% else %}
  {# ここからページネーションの開始 #}
  {% load pagination_tags %}
  {% autopaginate object_list 12 %}

  {# 数字表示 #}
  {% paginate %}
  {% for entry in object_list %}
  <dt>
    [{{ entry.id }}] <b><a href="/entries/detail/{{ entry.id }}">{{ entry.title }}</a></b>
    by {{ entry.name }}
    [<a href="mailto:{{ entry.email }}">mail</a>]
    [{% trans "post date" %}: {{ entry.create_at }}]
  </dt>

  <dd>
    {{ entry.content }}
  </dd>

  <dd class="operation">
    [<a href="/entries/update/{{ entry.id }}">{% trans "edit" %}</a>]
    [<a href="/entries/delete/{{ entry.id }}">{% trans "delete" %}</a>]
  </dd>
  <hr />
  {% endfor %}

  {# 数字表示 #}
  {% paginate %}
{% endif %}
<dd div class="operation">
  [<a href="/entries/create/">{% trans "add comment" %}</a>]
</dd>
{% endblock %}

entries/templates/entries/news_confirm_delete.html
{% extends "pages/index.html" %}
{% block news_content %}

{% if not user.is_anonymous %}
<form method="post" action="." accept-charset="utf-8">{% csrf_token %}
  <p>削除します。よろしいですか？</p><br />

  <input type="submit" />
  <input type="button" value="いいえ" onClick="location.href='/entries/'" />
</form>
<br />
{% endif %}
{% endblock %}

entries/templates/entries/news_detail.html
{% extends "pages/index.html" %}
{% block news_content %}

<dt>
  {{ objec.title }}
</dt>
<dd>
  {{ object.content|linebreaks }}
</dd>
<dd>
  -
  {{ object.date }}
  {% if news.date|date:"w" == '0' %}
  {# 日曜 #}
  (<font color="#FF0000">{{ news.date|date:"D" }}</font>)
  {% elif news.date|date:"w" == '6' %}
  {# 土曜 #}
  (<font color="#0000FF">{{ news.date|date:"D" }}</font>)
  {% else %}
  (<font color="#000000">{{ news.date|date:"D" }}</font>)
  {% endif %}
</dd>
</br />

<dd div class="operation">
  [<a href="/entries/update_news/{{ object.id }}">編集</a>]
  [<a href="/entries/delete_news/{{ object.id }}">削除</a>]
</dd>
<br />
{% endblock %}

entries/templates/entries/news_form.html
{% extends "pages/index.html" %}
{% block news_content %}
{% load i18n %}

{% for news in object_list %}
  <div>
    <img src="{{ STATIC_URL }}img/box.gif" width=10 height=10>
    <a href="/entries/detail_news/{{ news.id }}">{{ news.title }}</a>
    - {{ news.date }}
    {% if news.date|date:"w" == '0' %}
    {# 日曜 #}
    (<font color="#FF0000">{{ news.date|date:"D" }}</font>)
    {% elif news.date|date:"w" == '6' %}
    {# 土曜 #}
    (<font color="#0000FF">{{ news.date|date:"D" }}</font>)
    {% else %}
    (<font color="#000000">{{ news.date|date:"D" }}</font>)
    {% endif %}
    [<a href="/entries/update_news/{{ news.id }}">{% trans "edit" %}</a>]
    [<a href="/entries/delete_news/{{ news.id }}">{% trans "delete" %}</a>]
  </div>
  <hr />
{% endfor %}

{% if object %}
<h3>編集</h3><br />
{% else %}
<h3>新規作成</h3><br />
{% endif %}

{% if form.has_errors %}
  {% for field in form.fields %}
    {% if fields.error %}
      {{ field.error}}
    {% endif %}

  {% endfor %}
{% endif %}

<div class="validation">
  <form action="." method="post" accept-charset="utf-8">{% csrf_token %}
    <!-- タイトル -->
    <label for="id_title">{% trans "title" %}:</label>{{ form.title }}
    {% if form.title.errors %}
    <p>
      <error> {{ form.title.errors|join:", "}}</error>
    </p>
    {% endif %}
    <br/><br/>
    <!-- 内容 -->
    <label for="id_content">{% trans "content" %}:</label>{{ form.content }}
    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    {% endif %}
    <br /><br />
    <!-- 日付 -->
    <!-- 
    <label for="id_date">日付：</label>{{ form.date }}
    --> 
    <p><label for="id_date">{% trans "date" %}:</label><input value="{{form.date.value|date:"c"}}" id="id_date" name="date" type="text" class="jquery-ui-datepicker"/></p>

    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    <br /><br />
    {% endif %}
    <p><input type="submit" value="{% trans "save" %}" /></p><br />
  </form>
</div>
{% endblock %}